/**
 * Seed Experts Library
 *
 * Migrates EXPERT_DATABASE (hardcoded) to experts table as shared library
 * All seeded experts have userId = null (shared library)
 */

import { db } from '../src/client'
import { experts } from '../src/schema'
import { getAllExperts } from '../../quoorum/src/expert-database'
import { EXPERT_CATEGORIES } from '../../quoorum/src/config/expert-config'
import type { ExpertProfile } from '../../quoorum/src/expert-database'
import { eq, and, isNull } from 'drizzle-orm'

/**
 * Map old categories to new library categories
 * - empresa: Business-related (positioning, pricing, product, growth, sales, operations, fundraising, technical)
 * - vida-personal: Personal life, relationships, health, hobbies
 * - historicos: Historical figures, philosophers, leaders
 * - general: Default/catch-all (critical thinking, meta-analysis, etc.)
 */
function mapCategory(expertId: string, oldCategory: string | undefined): string {
  // Use EXPERT_CATEGORIES mapping if available
  const categoryFromMapping = EXPERT_CATEGORIES[expertId as keyof typeof EXPERT_CATEGORIES]
  const category = categoryFromMapping || oldCategory || 'general'

  const categoryMap: Record<string, string> = {
    // Business categories → empresa
    positioning: 'empresa',
    conversion: 'empresa',
    sales: 'empresa',
    pricing: 'empresa',
    product: 'empresa',
    growth: 'empresa',
    operations: 'empresa',
    technical: 'empresa', // AI/ML technical experts are business-related
    fundraising: 'empresa',
    // General/critical thinking → general
    general: 'general',
    // vida-personal and historicos can be added later when we have experts in those categories
    'vida-personal': 'vida-personal',
    'historicos': 'historicos',
  }

  // Special case: critic is always 'general'
  if (expertId === 'critic') {
    return 'general'
  }

  return categoryMap[category] || 'empresa'
}

/**
 * Convert ExpertProfile to experts table format
 * Note: id will be auto-generated by DB (UUID), we don't set it explicitly
 */
function expertProfileToExpert(expert: ExpertProfile) {
  return {
    // id: auto-generated by DB (UUID)
    userId: null, // Library expert (shared)
    name: expert.name,
    expertise: Array.isArray(expert.expertise) ? expert.expertise.join(', ') : String(expert.expertise || ''),
    description: expert.perspective || undefined,
    systemPrompt: expert.systemPrompt,
    aiConfig: {
      provider: expert.provider,
      model: expert.modelId,
      temperature: expert.temperature,
    },
    category: mapCategory(expert.id, expert.title?.toLowerCase()),
    isActive: true,
    libraryExpertId: null, // Not a fork
  }
}

/**
 * Seed experts library from EXPERT_DATABASE
 */
async function seedExpertsLibrary() {
  console.log('[SEED] Seeding experts library...')

  try {
    // Get all experts from EXPERT_DATABASE
    const expertProfiles = getAllExperts()
    console.log(`[INFO] Found ${expertProfiles.length} experts in EXPERT_DATABASE`)

    // Check how many already exist in DB
    const existingExperts = await db
      .select({ id: experts.id })
      .from(experts)
      .where(isNull(experts.userId))

    console.log(`[INFO] Found ${existingExperts.length} existing library experts in DB`)

    // Convert to experts table format
    const expertsToInsert = expertProfiles.map(expertProfileToExpert)

    // Insert all experts (id auto-generated by DB)
    // Skip duplicates by checking name + userId = null combination
    let inserted = 0
    let skipped = 0

    for (const expert of expertsToInsert) {
      // Check if expert with same name already exists in library
      const existing = await db
        .select({ id: experts.id })
        .from(experts)
        .where(and(isNull(experts.userId), eq(experts.name, expert.name)))
        .limit(1)

      if (existing.length > 0) {
        skipped++
        continue
      }

      try {
        await db.insert(experts).values(expert)
        inserted++
      } catch (error) {
        console.error(`[ERROR] Error inserting expert ${expert.name}:`, error)
      }
    }

    console.log(`[OK] Inserted ${inserted} new experts`)
    if (skipped > 0) {
      console.log(`[INFO] Skipped ${skipped} existing experts`)
    }

    // Verify final count
    const finalCount = await db
      .select({ id: experts.id })
      .from(experts)
      .where(isNull(experts.userId))

    console.log(`[INFO] Final library experts count: ${finalCount.length}`)
    console.log('[OK] Experts library seed complete!')
  } catch (error) {
    console.error('[ERROR] Error seeding experts library:', error)
    throw error
  }
}

// Run if executed directly
if (import.meta.url.endsWith(process.argv[1]?.replace(/\\/g, '/')) || import.meta.url.includes('seed-experts.ts')) {
  seedExpertsLibrary()
    .then(() => {
      console.log('[OK] Seed completed successfully')
      process.exit(0)
    })
    .catch((error) => {
      console.error('[ERROR] Seed failed:', error)
      process.exit(1)
    })
}

export { seedExpertsLibrary }
